# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
      - uses: subosito/flutter-action@v1
        with:
          version: '2.8'

      - name: Install dependencies
        run: flutter pub get

      # - name: Verify formatting
        # run: flutter format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run flutter tests
        run: flutter test

      - name: Run Android build
        run: flutter build apk --target=example/lib/main.dart
